apiVersion: v1
kind: Pod
metadata:
  name: busytestenv
  namespace: test
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
    name: busybox
    envFrom:
      - configMapRef:
          name: twickets-botmain-config
      - secretRef:
          name: prowl-api-key
      - secretRef:
          name: twickets-api-key-secret
      - secretRef:
          name: twickets-email-alt
      - secretRef:
          name: twickets-password-alt
      - secretRef:
          name: telegram-keys

  restartPolicy: Always
