apiVersion: apps/v1
kind: Deployment
metadata:
  name: twicketsbotcamping
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twicketsbotcamping
  template:
    metadata:
      labels:
        app: twicketsbotcamping
    spec:
      containers:
      - name: twicketsbot
        image: registry.sharpred.work/twicketsbot:2.6
        envFrom:
        - configMapRef:
            name: twickets-botcamping-config
        - secretRef:
            name: prowl-api-key
        - secretRef:
            name: twickets-api-key-secret
        - secretRef:
            name: twickets-email
        - secretRef:
            name: twickets-password
        - secretRef:
            name: telegram-keys
      imagePullSecrets:
      - name: regcred
