apiVersion: apps/v1
kind: Deployment
metadata:
  name: twicketsbot
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twicketsbot
  template:
    metadata:
      labels:
        app: twicketsbot
    spec:
      containers:
      - name: twicketsbot
        image: registry.sharpred.work/twicketsbot:2.1
        envFrom:
          - configMapRef:
              name: twickets-bot-config
          - secretRef:
              name: prowl-api-key
          - secretRef:
              name: twickets-api-key-secret
          - secretRef:
              name: twickets-email
          - secretRef:
              name: twickets-password
          - secretRef:
              name: telegram-keys
      imagePullSecrets:
        - name: regcred